"""
Career Database - Future-Oriented Professions Catalog
Based on Ikigai framework and future job market trends
"""

FUTURE_CAREERS = [
    {
        "id": "ai_ml_engineer",
        "title": "AI/Machine Learning Engineer",
        "description": "Design, build, and deploy AI systems that solve real-world problems",
        "passion_keywords": ["automation", "innovation", "data", "problem-solving", "AI", "learning"],
        "skill_keywords": ["python", "tensorflow", "pytorch", "statistics", "mathematics", "data analysis"],
        "value_keywords": ["progress", "innovation", "creating", "impact", "continuous learning"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (150000, 250000),
        "future_oriented": True,
        "future_relevance": "Essential for 2030+",
        "required_skills": ["Python", "TensorFlow/PyTorch", "Statistics", "Mathematics", "Data Engineering"],
        "learning_path": ["Python basics", "Statistics & Math", "ML libraries", "Advanced ML", "Deep Learning"],
    },
    {
        "id": "data_scientist",
        "title": "Data Scientist",
        "description": "Extract insights from data to drive business decisions and innovation",
        "passion_keywords": ["data", "analytics", "patterns", "insights", "visualization", "problem-solving"],
        "skill_keywords": ["python", "sql", "tableau", "statistics", "pandas", "analysis"],
        "value_keywords": ["insights", "impact", "evidence-based", "creativity", "discovery"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (130000, 200000),
        "future_oriented": True,
        "future_relevance": "Critical role in AI era",
        "required_skills": ["Python", "SQL", "Statistics", "Data Visualization", "Big Data Tools"],
        "learning_path": ["Statistics", "Python", "SQL", "Data Viz", "ML Basics"],
    },
    {
        "id": "software_architect",
        "title": "Software Architect",
        "description": "Design scalable, secure, and efficient software systems",
        "passion_keywords": ["design", "systems", "architecture", "problem-solving", "scaling", "innovation"],
        "skill_keywords": ["system design", "cloud", "microservices", "databases", "coding"],
        "value_keywords": ["quality", "elegance", "impact", "responsibility", "mastery"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (140000, 220000),
        "future_oriented": True,
        "future_relevance": "Always in demand",
        "required_skills": ["System Design", "Cloud (AWS/Azure)", "Microservices", "Databases", "Leadership"],
        "learning_path": ["Systems thinking", "Cloud basics", "Microservices", "Design patterns", "Leadership"],
    },
    {
        "id": "cybersecurity_specialist",
        "title": "Cybersecurity Specialist",
        "description": "Protect organizations from digital threats and vulnerabilities",
        "passion_keywords": ["security", "protection", "problem-solving", "risk", "defense", "technology"],
        "skill_keywords": ["networking", "security protocols", "cryptography", "penetration testing", "tools"],
        "value_keywords": ["safety", "responsibility", "trust", "protection", "excellence"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (120000, 200000),
        "future_oriented": True,
        "future_relevance": "Critical in 2030+",
        "required_skills": ["Networking", "Security Protocols", "Penetration Testing", "Cryptography", "Tools"],
        "learning_path": ["Networking basics", "Security fundamentals", "Tools & techniques", "Pen testing", "Advanced"],
    },
    {
        "id": "product_manager_tech",
        "title": "Tech Product Manager",
        "description": "Lead the vision, strategy, and development of technology products",
        "passion_keywords": ["innovation", "user experience", "leadership", "strategy", "impact", "vision"],
        "skill_keywords": ["product strategy", "analytics", "user research", "communication", "leadership"],
        "value_keywords": ["impact", "user satisfaction", "innovation", "leadership", "vision"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (140000, 210000),
        "future_oriented": True,
        "future_relevance": "Increasingly important",
        "required_skills": ["Product Strategy", "Analytics", "User Research", "Communication", "Leadership"],
        "learning_path": ["User research", "Analytics", "Product strategy", "Communication", "Leadership"],
    },
    {
        "id": "ux_designer",
        "title": "UX/UI Designer",
        "description": "Create beautiful, intuitive digital experiences that delight users using evidence-based design and user psychology",
        "passion_keywords": ["design", "user experience", "creativity", "aesthetics", "usability", "innovation", "ux", "drawing", "visual"],
        "skill_keywords": ["design", "figma", "prototyping", "user research", "psychology", "tools", "visual communication"],
        "value_keywords": ["creativity", "user satisfaction", "aesthetics", "empathy", "impact", "financial security"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (100000, 160000),
        "future_oriented": True,
        "future_relevance": "Essential skill for all products",
        "required_skills": ["UI/UX Design", "Figma/Sketch", "Prototyping", "User Research", "Psychology", "Visual Science"],
        "learning_path": ["Design fundamentals", "Tools", "User research", "Prototyping", "Advanced UX"],
    },
    {
        "id": "science_illustrator",
        "title": "Medical & Science Illustrator",
        "description": "Create detailed anatomical drawings and scientific visualizations for biotech, education, and research institutions",
        "passion_keywords": ["biology", "illustration", "drawing", "science", "explaining", "anatomical", "flow"],
        "skill_keywords": ["drawing", "digital illustration", "anatomy", "biology", "visual communication", "3d modeling"],
        "value_keywords": ["education", "clarity", "impact", "discovery", "accuracy", "financial stability"],
        "growth_potential": "High",
        "market_demand": "Niche/High",
        "salary_range": (90000, 150000),
        "future_oriented": True,
        "future_relevance": "Critical for high-end biotech and scientific communication",
        "required_skills": ["Scientific Illustration", "Anatomy", "Biology", "Visual Communication", "Digital Media"],
        "learning_path": ["Fundamental drawing", "Advanced biology", "Digital illustration software", "Medical communication"],
    },
    {
        "id": "biotech_ux_researcher",
        "title": "Biotech UX Researcher",
        "description": "Combine biological expertise with UX research to design intuitive laboratory and medical software systems",
        "passion_keywords": ["biotech", "research", "user experience", "science", "innovation", "impact"],
        "skill_keywords": ["ux research", "biology", "data analysis", "user testing", "biotechnology", "visual science"],
        "value_keywords": ["healthcare", "innovation", "impact", "financial benefit", "career stability"],
        "growth_potential": "Very High",
        "market_demand": "High",
        "salary_range": (130000, 210000),
        "future_oriented": True,
        "future_relevance": "Essential for the digitalization of biotech and healthcare",
        "required_skills": ["UX Research", "Biology", "Experimental Design", "Data Visualization", "Communication"],
        "learning_path": ["UX principles", "Biology foundation", "Human factors in health", "Biotech data systems"],
    },
    {
        "id": "cloud_architect",
        "title": "Cloud Solutions Architect",
        "description": "Design and implement scalable cloud infrastructure solutions",
        "passion_keywords": ["infrastructure", "scalability", "cloud", "optimization", "problem-solving", "systems"],
        "skill_keywords": ["aws", "azure", "kubernetes", "devops", "architecture", "infrastructure"],
        "value_keywords": ["efficiency", "scalability", "innovation", "reliability", "mastery"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (140000, 230000),
        "future_oriented": True,
        "future_relevance": "Critical infrastructure role",
        "required_skills": ["AWS/Azure", "Kubernetes", "DevOps", "Architecture", "Networking"],
        "learning_path": ["Cloud fundamentals", "Containerization", "Orchestration", "Infrastructure", "Advanced"],
    },
    {
        "id": "quantum_computing_dev",
        "title": "Quantum Computing Developer",
        "description": "Develop solutions using quantum computing technology for complex problems",
        "passion_keywords": ["innovation", "cutting-edge", "physics", "quantum", "problem-solving", "future"],
        "skill_keywords": ["quantum mechanics", "qiskit", "python", "physics", "mathematics"],
        "value_keywords": ["innovation", "progress", "challenge", "future", "discovery"],
        "growth_potential": "Extremely High",
        "market_demand": "Growing",
        "salary_range": (160000, 250000),
        "future_oriented": True,
        "future_relevance": "Next frontier technology",
        "required_skills": ["Quantum Mechanics", "Qiskit", "Python", "Physics", "Mathematics"],
        "learning_path": ["Quantum physics", "Qiskit basics", "Python", "Advanced quantum", "Research"],
    },
    {
        "id": "sustainability_tech_lead",
        "title": "Sustainability Technology Lead",
        "description": "Use technology to solve environmental and sustainability challenges",
        "passion_keywords": ["environment", "sustainability", "climate", "impact", "innovation", "purpose"],
        "skill_keywords": ["data analysis", "iot", "sensors", "software", "systems thinking"],
        "value_keywords": ["environment", "social impact", "future generation", "responsibility", "purpose"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (110000, 180000),
        "future_oriented": True,
        "future_relevance": "Essential for 2030+ climate goals",
        "required_skills": ["Data Analysis", "IoT", "Software Development", "Systems Thinking", "Domain Knowledge"],
        "learning_path": ["Environmental basics", "IoT/sensors", "Data analysis", "Software", "Specialized"],
    },
    {
        "id": "biotech_engineer",
        "title": "Biotech/Bioinformatics Engineer",
        "description": "Apply technology and engineering to biological and medical challenges",
        "passion_keywords": ["biology", "healthcare", "innovation", "research", "problem-solving", "impact"],
        "skill_keywords": ["bioinformatics", "python", "data analysis", "biology", "statistics"],
        "value_keywords": ["healthcare", "research", "impact", "discovery", "helping people"],
        "growth_potential": "Very High",
        "market_demand": "High",
        "salary_range": (120000, 200000),
        "future_oriented": True,
        "future_relevance": "Critical for biotech revolution",
        "required_skills": ["Bioinformatics", "Python", "Statistics", "Biology", "Data Analysis"],
        "learning_path": ["Biology basics", "Python", "Bioinformatics tools", "Statistics", "Advanced"],
    },
    {
        "id": "ar_vr_developer",
        "title": "AR/VR Developer",
        "description": "Create immersive experiences using augmented and virtual reality",
        "passion_keywords": ["immersive", "3d", "innovation", "creativity", "gaming", "experience"],
        "skill_keywords": ["unity", "unreal", "3d programming", "graphics", "user experience"],
        "value_keywords": ["creativity", "innovation", "user experience", "cutting-edge", "impact"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (110000, 180000),
        "future_oriented": True,
        "future_relevance": "Growing metaverse role",
        "required_skills": ["Unity/Unreal", "3D Programming", "Graphics", "Physics", "UX"],
        "learning_path": ["3D basics", "Game engine", "Programming", "Graphics", "Advanced VR"],
    },
    {
        "id": "blockchain_engineer",
        "title": "Blockchain Engineer",
        "description": "Build decentralized systems using blockchain and Web3 technologies",
        "passion_keywords": ["decentralization", "blockchain", "crypto", "innovation", "finance", "systems"],
        "skill_keywords": ["solidity", "ethereum", "web3", "cryptography", "smart contracts"],
        "value_keywords": ["decentralization", "innovation", "disruption", "future", "transparency"],
        "growth_potential": "High",
        "market_demand": "Growing",
        "salary_range": (120000, 220000),
        "future_oriented": True,
        "future_relevance": "Web3 and DeFi future",
        "required_skills": ["Solidity", "Ethereum", "Web3", "Cryptography", "Smart Contracts"],
        "learning_path": ["Blockchain basics", "Solidity", "Web3 tools", "Smart contracts", "Advanced"],
    },
    {
        "id": "digital_twin_architect",
        "title": "Digital Twin Architect",
        "description": "Create digital replicas of physical assets, processes, and systems for simulation and optimization",
        "passion_keywords": ["simulation", "digital twins", "modeling", "iot", "systems", "innovation"],
        "skill_keywords": ["3d modeling", "iot", "digital twins", "simulation", "python", "industrial iot"],
        "value_keywords": ["efficiency", "innovation", "precision", "future", "stability"],
        "growth_potential": "Exponential",
        "market_demand": "High",
        "salary_range": (130000, 210000),
        "future_oriented": True,
        "future_relevance": "Key for Industry 4.0",
        "required_skills": ["Industrial IoT", "Simulation Tools", "3D Modeling", "Python", "Systems Engineering"],
        "learning_path": ["IoT basics", "3D modeling", "Simulation theory", "Digital Twin platforms", "Project"],
    },
    {
        "id": "ai_ethics_compliance_lead",
        "title": "AI Ethics & Compliance Lead",
        "description": "Ensure AI systems are developed and deployed fairly, transparently, and safely",
        "passion_keywords": ["ethics", "fairness", "ai safety", "responsibility", "justice", "policy"],
        "skill_keywords": ["ai governance", "risk assessment", "compliance", "ethics", "communication"],
        "value_keywords": ["fairness", "justice", "responsibility", "trust", "human-centric"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (120000, 200000),
        "future_oriented": True,
        "future_relevance": "Critical for regulated AI in 2030+",
        "required_skills": ["AI Policy", "Ethics Frameworks", "Risk Management", "Compliance", "Effective Communication"],
        "learning_path": ["Philosophy/Ethics", "AI basics", "Governance frameworks", "Regulatory law", "Policy"],
    },
    {
        "id": "renewable_energy_consultant",
        "title": "Renewable Energy Consultant",
        "description": "Advise organizations on transitioning to sustainable energy sources like solar, wind, and green hydrogen.",
        "passion_keywords": ["sustainability", "renewable energy", "environment", "climate action", "green tech"],
        "skill_keywords": ["energy auditing", "solar pv", "wind energy", "policy analysis", "project management"],
        "value_keywords": ["clean energy", "innovation", "conservation", "responsibility", "efficiency"],
        "growth_potential": "Very High",
        "market_demand": "High",
        "salary_range": (85000, 155000),
        "future_oriented": True,
        "future_relevance": "O*NET Bright Outlook: High growth in green transition",
        "required_skills": ["Energy auditing", "Project Management", "Technical writing", "Financial analysis", "Policy knowledge"]
    },
    {
        "id": "nanotechnology_engineer",
        "title": "Nanotechnology Engineer",
        "description": "Design and engineer materials and devices at the molecular level for medicine, electronics, and energy.",
        "passion_keywords": ["nanotech", "innovation", "physics", "molecules", "precision"],
        "skill_keywords": ["micro-manufacturing", "molecular modeling", "material science", "analytical chemistry"],
        "value_keywords": ["discovery", "excellence", "impact", "innovation", "precision"],
        "growth_potential": "High",
        "market_demand": "Growing",
        "salary_range": (95000, 175000),
        "future_oriented": True,
        "future_relevance": "Critical for next-gen material science",
        "required_skills": ["Material Science", "Molecular Modeling", "Analytical Chemistry", "Microscopy"]
    },
    {
        "id": "telemedicine_specialist",
        "title": "Telemedicine Specialist",
        "description": "Coordinate and deliver healthcare services through digital platforms and remote monitoring technologies.",
        "passion_keywords": ["digital health", "care", "healthcare", "technology", "helping"],
        "skill_keywords": ["remote diagnostics", "digital communication", "patient care", "hipaa compliance"],
        "value_keywords": ["accessibility", "care", "efficiency", "humanity", "health"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (90000, 160000),
        "future_oriented": True,
        "future_relevance": "O*NET: Increasing demand for remote health delivery",
        "required_skills": ["Clinical Knowledge", "Digital Platform Proficiency", "Patient Communication", "Telehealth Regulations"]
    },
    {
        "id": "drone_logistics_manager",
        "title": "Drone Logistics Manager",
        "description": "Design and manage delivery networks using autonomous aerial vehicles for logistics and medical supply transport.",
        "passion_keywords": ["automation", "aviation", "logistics", "efficiency", "robotics"],
        "skill_keywords": ["fleet management", "drone operation", "supply chain", "geographic information systems"],
        "value_keywords": ["efficiency", "innovation", "safety", "progress", "reliability"],
        "growth_potential": "Very High",
        "market_demand": "Growing",
        "salary_range": (110000, 190000),
        "future_oriented": True,
        "future_relevance": "Revolutionizing last-mile delivery by 2030",
        "required_skills": ["GIS", "Supply Chain Optimization", "Aviation Regulations", "Fleet Management"]
    },
    {
        "id": "bio-art_designer",
        "title": "Bio-Art Designer",
        "description": "Fuse biology and visual art to create living sculptures, synthetic biological aesthetics, and educational exhibits.",
        "passion_keywords": ["bio-art", "biology", "drawing", "creativity", "aesthetics"],
        "skill_keywords": ["biological modeling", "visual design", "wet lab techniques", "speculative design"],
        "value_keywords": ["creativity", "innovation", "expression", "curiosity", "beauty"],
        "growth_potential": "Medium",
        "market_demand": "Niche/Growing",
        "salary_range": (75000, 140000),
        "future_oriented": True,
        "future_relevance": "Emerging intersection of biotech and creative industries",
        "required_skills": ["Digital Illustration", "Molecular Biology Basics", "Concept Art", "Lab Safety"]
    },
    {
        "id": "smart_city_planner",
        "title": "Smart City Planner",
        "description": "Design urban environments that integrate IoT, sustainable transport, and data-driven infrastructure management.",
        "passion_keywords": ["urban design", "sustainability", "iot", "infrastructure", "community"],
        "skill_keywords": ["urban planning software", "data visualization", "gis", "systems thinking"],
        "value_keywords": ["efficiency", "community", "environment", "innovation", "equity"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (105000, 185000),
        "future_oriented": True,
        "future_relevance": "O*NET: Urban planning pivoting to tech-integrated cities",
        "required_skills": ["GIS", "IoT Integration", "Project Management", "Urban Policy"]
    },
    {
        "id": "space_technician",
        "title": "Satellite & Space Technician",
        "description": "Build, maintain, and launch satellite systems and hardware for communication and space exploration research.",
        "passion_keywords": ["space", "exploration", "engineering", "hardware", "aerospace"],
        "skill_keywords": ["precision manufacturing", "avionics", "satellite communication", "telemetry"],
        "value_keywords": ["discovery", "precision", "courage", "impact", "exploration"],
        "growth_potential": "High",
        "market_demand": "Growing",
        "salary_range": (90000, 170000),
        "future_oriented": True,
        "future_relevance": "Booming commercial space industry (SpaceX, Blue Origin)",
        "required_skills": ["Avionics", "Electrical Engineering", "RF Communication", "Robotics"]
    },
    {
        "id": "robotics_process_automation_dev",
        "title": "RPA Developer",
        "description": "Develop software robots to automate repetitive business processes and legacy system interactions.",
        "passion_keywords": ["automation", "efficiency", "software", "logic", "optimization"],
        "skill_keywords": ["uipath", "python", "process mapping", "scripting", "api integration"],
        "value_keywords": ["efficiency", "precision", "progress", "reliability", "improvement"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (115000, 185000),
        "future_oriented": True,
        "future_relevance": "Essential for corporate digital transformation",
        "required_skills": ["Python", "UiPath/BluePrism", "API Integration", "Business Logic"]
    },
    {
        "id": "neuro-interface_engineer",
        "title": "Neuro-Interface Engineer",
        "description": "Develop Brain-Computer Interface (BCI) technologies for medical recovery and advanced human-computer interaction.",
        "passion_keywords": ["neuroscience", "bcis", "technology", "cognitive", "healthcare"],
        "skill_keywords": ["signal processing", "neuroscience", "python", "embedded systems", "ml"],
        "value_keywords": ["humanity", "health", "innovation", "potential", "discovery"],
        "growth_potential": "Exponential",
        "market_demand": "Research-High",
        "salary_range": (145000, 240000),
        "future_oriented": True,
        "future_relevance": "Neuralink era technologies",
        "required_skills": ["Signal Processing", "Neuroscience basics", "Embedded Systems", "Machine Learning"]
    },
    {
        "id": "vertical_farming_specialist",
        "title": "Vertical Farming Specialist",
        "description": "Optimize indoor growing environments using hydroponics, aeroponics, and automated environmental controls.",
        "passion_keywords": ["agriculture", "sustainability", "food security", "automation", "nature"],
        "skill_keywords": ["hydroponics", "iot sensors", "botany", "resource management"],
        "value_keywords": ["sustainability", "health", "innovation", "protection", "efficiency"],
        "growth_potential": "High",
        "market_demand": "Growing",
        "salary_range": (80000, 145000),
        "future_oriented": True,
        "future_relevance": "Key for urban food resilience in 2030+",
        "required_skills": ["Hydroponic Systems", "IoT Management", "Plant Biology", "Operations"]
    },
    {
        "id": "circular_economy_manager",
        "title": "Circular Economy Manager",
        "description": "Design business models and supply chains that eliminate waste through reuse, recycling, and resource regeneration.",
        "passion_keywords": ["sustainability", "waste reduction", "business", "innovation", "nature"],
        "skill_keywords": ["life cycle assessment", "supply chain management", "green marketing", "logistics"],
        "value_keywords": ["responsibility", "conservation", "harmony", "innovation", "ethics"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (100000, 175000),
        "future_oriented": True,
        "future_relevance": "Shift toward regenerative business models",
        "required_skills": ["Life Cycle Assessment", "Supply Chain", "Business Strategy", "Sustainability Advocacy"]
    },
    {
        "id": "digital_curator",
        "title": "Digital Assets Curator",
        "description": "Manage and preserve digital collections, NFTs, and virtual real estate in decentralized platforms and museums.",
        "passion_keywords": ["art", "digital culture", "history", "web3", "organization"],
        "skill_keywords": ["metadata standards", "blockchain", "digital archiving", "visual storytelling"],
        "value_keywords": ["preservation", "innovation", "culture", "meaning", "creativity"],
        "growth_potential": "Medium",
        "market_demand": "Growing",
        "salary_range": (70000, 135000),
        "future_oriented": True,
        "future_relevance": "The future of cultural heritage management",
        "required_skills": ["Database Management", "Art History", "Blockchain Basics", "Digital Ethics"]
    },
    {
        "id": "autonomous_transport_operator",
        "title": "Autonomous Transport Operator",
        "description": "Monitor and manage fleets of autonomous vehicles, troubleshooting system interventions and optimizing routes.",
        "passion_keywords": ["automotive", "ai", "transportation", "safety", "efficiency"],
        "skill_keywords": ["system monitoring", "troubleshooting", "telemetry analysis", "urban navigation"],
        "value_keywords": ["safety", "efficiency", "reliability", "progress", "service"],
        "growth_potential": "Very High",
        "market_demand": "High",
        "salary_range": (90000, 150000),
        "future_oriented": True,
        "future_relevance": "Pivotal as passenger fleets transition to self-driving",
        "required_skills": ["System Monitoring", "Technical Support", "Urban Logistics", "Incident Management"]
    },
    {
        "id": "synthetic_biologist",
        "title": "Synthetic Biologist",
        "description": "Redesign organisms for useful purposes by engineering them to have new abilities or produce specific molecules.",
        "passion_keywords": ["biology", "engineering", "genetics", "innovation", "design"],
        "skill_keywords": ["crispr", "genetic sequencing", "lab automation", "python"],
        "value_keywords": ["discovery", "impact", "creativity", "excellence", "health"],
        "growth_potential": "Very High",
        "market_demand": "High",
        "salary_range": (130000, 220000),
        "future_oriented": True,
        "future_relevance": "Foundational for 21st-century manufacturing",
        "required_skills": ["CRISPR", "Gene Editing Software", "Molecular Biology", "Lab Automation"]
    },
    {
        "id": "data_privacy_officer",
        "title": "Data Privacy Officer",
        "description": "Ensure organizations comply with data protection laws (GDPR, CCPA) while managing user data ethically and transparently.",
        "passion_keywords": ["privacy", "ethics", "rights", "law", "technology"],
        "skill_keywords": ["compliance auditing", "risk management", "legal knowledge", "data mapping"],
        "value_keywords": ["integrity", "justice", "security", "trust", "transparency"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (125000, 210000),
        "future_oriented": True,
        "future_relevance": "O*NET: High demand as data regulations expand globally",
        "required_skills": ["Legal Analysis", "Data Auditing", "Privacy Frameworks (ISO/NIST)", "Communication"]
    },
    {
        "id": "customer_experience_architect",
        "title": "Customer Experience (CX) Architect",
        "description": "Map and design the end-to-end user journey across digital and physical touchpoints to drive loyalty and value.",
        "passion_keywords": ["psychology", "design", "business", "empathy", "experience"],
        "skill_keywords": ["journey mapping", "data analytics", "design thinking", "cx platform management"],
        "value_keywords": ["empathy", "satisfaction", "innovation", "connection", "impact"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (110000, 190000),
        "future_oriented": True,
        "future_relevance": "Critical for brand differentiation in AI-driven markets",
        "required_skills": ["Design Thinking", "CX Analytics", "Journey Mapping", "Strategic Planning"]
    },
    {
        "id": "edtech_developer",
        "title": "EdTech Learning Architect",
        "description": "Create personalized learning environments and tools using AI and neuro-education principles for lifelong learning.",
        "passion_keywords": ["education", "technology", "helping", "learning", "innovation"],
        "skill_keywords": ["instructional design", "gamification", "lms", "python"],
        "value_keywords": ["growth", "innovation", "equality", "knowledge", "impact"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (95000, 165000),
        "future_oriented": True,
        "future_relevance": "O*NET: Training and development moving to AI personalization",
        "required_skills": ["Instructional Design", "LMS Platforms", "Psychology of Learning", "Data Analytics"]
    },
    {
        "id": "cloud_security_engineer",
        "title": "Cloud Security Engineer",
        "description": "Securing cloud-based infrastructure and services from complex cyber attacks and data breaches.",
        "passion_keywords": ["security", "cloud", "defense", "problem-solving", "networking"],
        "skill_keywords": ["aws/azure security", "iam", "incident response", "threat modeling"],
        "value_keywords": ["safety", "trust", "protection", "excellence", "reliability"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (140000, 230000),
        "future_oriented": True,
        "future_relevance": "Critical as 90%+ of enterprises move to cloud",
        "required_skills": ["Cloud Architecture", "Identity & Access Management", "Encryption", "Threat Detection"]
    },
    {
        "id": "quant_trader_ai",
        "title": "AI Quantitative Trader",
        "description": "Develop and deploy algorithmic trading strategies using machine learning to navigate global financial markets.",
        "passion_keywords": ["finance", "ai", "math", "strategy", "competition"],
        "skill_keywords": ["python", "quantitative analysis", "ml", "financial modeling"],
        "value_keywords": ["independence", "financial security", "innovation", "precision", "mastery"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (150000, 350000),
        "future_oriented": True,
        "future_relevance": "Integration of LLMs into financial forecasting",
        "required_skills": ["Advanced Python", "Statistics", "Machine Learning", "Financial Markets"]
    },
    {
        "id": "precision_medicine_technician",
        "title": "Precision Medicine Technician",
        "description": "Assist in tailoring medical treatments to individual genetic profiles using genomic sequencing and software tools.",
        "passion_keywords": ["genetics", "healthcare", "personalization", "science", "helping"],
        "skill_keywords": ["genomics", "bioinformatics basics", "patient data management", "lab tech"],
        "value_keywords": ["care", "precision", "innovation", "health", "humanity"],
        "growth_potential": "Very High",
        "market_demand": "High",
        "salary_range": (85000, 155000),
        "future_oriented": True,
        "future_relevance": "O*NET: High growth expected in personalized healthcare",
        "required_skills": ["Genomic Sequencing", "Data Integrity", "Biology", "Client Communication"]
    },
    {
        "id": "international_relations_specialist",
        "title": "International Relations Specialist",
        "description": "Analyze global trends and manage relationships between nations or organizations to foster peace and collaboration.",
        "passion_keywords": ["negotiation", "global affairs", "cultures", "diplomacy", "politics", "travel"],
        "skill_keywords": ["conflict resolution", "foreign languages", "cross-cultural communication", "analysis", "public speaking"],
        "value_keywords": ["peace", "global unity", "influence", "collaboration", "justice"],
        "growth_potential": "High",
        "market_demand": "Medium-High",
        "salary_range": (70000, 130000),
        "future_oriented": True,
        "future_relevance": "Essential for human-centric roles",
        "required_skills": ["Diplomacy", "Strategic Thinking", "Research", "Public Speaking", "Political Analysis"],
        "learning_path": ["Fundamentals", "Advanced Workshop", "Practical Experience", "Certification", "Mastery"]
    },
    {
        "id": "pr_communications_manager",
        "title": "Public Relations & Communications Manager",
        "description": "Craft and manage the public image of brands or individuals through storytelling and media relationships.",
        "passion_keywords": ["socializing", "storytelling", "media", "influence", "networking", "brand building"],
        "skill_keywords": ["writing", "media relations", "persuasion", "crisis management", "digital marketing"],
        "value_keywords": ["connection", "reputation", "influence", "creativity", "trust"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (80000, 150000),
        "future_oriented": True,
        "future_relevance": "Essential for human-centric roles",
        "required_skills": ["Media Strategy", "Press Release Writing", "Public Speaking", "Digital PR", "Crisis Communication"],
        "learning_path": ["Fundamentals", "Advanced Workshop", "Practical Experience", "Certification", "Mastery"]
    },
    {
        "id": "digital_content_strategist",
        "title": "Digital Content Strategist",
        "description": "Plan and oversee online content that engages audiences and builds communities for modern brands and influencers.",
        "passion_keywords": ["connecting with people", "social media", "trends", "creativity", "communities"],
        "skill_keywords": ["storytelling", "data analytics", "content planning", "editing", "audience engagement"],
        "value_keywords": ["influence", "community building", "creativity", "connection", "innovation"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (75000, 140000),
        "future_oriented": True,
        "future_relevance": "Essential for human-centric roles",
        "required_skills": ["Social Media Management", "Content Analytics", "Copywriting", "SEO", "Visual Storytelling"],
        "learning_path": ["Fundamentals", "Advanced Workshop", "Practical Experience", "Certification", "Mastery"]
    },
    {
        "id": "corporate_negotiator",
        "title": "Corporate Negotiator & Mediator",
        "description": "Help businesses reach agreements and resolve complex disputes through expert communication and strategy.",
        "passion_keywords": ["doing good negotiation", "winning", "problem-solving", "persuasion", "strategy"],
        "skill_keywords": ["negotiation", "conflict resolution", "empathy", "listening", "logical reasoning"],
        "value_keywords": ["fairness", "impact", "resolution", "financial security", "harmony"],
        "growth_potential": "High",
        "market_demand": "High",
        "salary_range": (90000, 180000),
        "future_oriented": True,
        "future_relevance": "Essential for human-centric roles",
        "required_skills": ["Advanced Negotiation", "Dispute Resolution", "Psychology", "Contract Law Basics", "Strategic Communication"],
        "learning_path": ["Fundamentals", "Advanced Workshop", "Practical Experience", "Certification", "Mastery"]
    },
    {
        "id": "sales_account_executive",
        "title": "Tech Sales & Account Executive",
        "description": "Build relationships with business clients and persuade them to adopt innovative technology solutions.",
        "passion_keywords": ["persuasion", "meeting people", "targets", "closing deals", "entrepreneurship"],
        "skill_keywords": ["sales strategy", "customer relationship management", "negotiation", "presentation", "resilience"],
        "value_keywords": ["wealth", "connection", "influence", "achievement", "competition"],
        "growth_potential": "Very High",
        "market_demand": "Very High",
        "salary_range": (90000, 200000),
        "future_oriented": True,
        "future_relevance": "Essential for human-centric roles",
        "required_skills": ["CRM Software", "Sales Prospecting", "Relationship Management", "Public Speaking", "Value-Based Selling"],
        "learning_path": ["Fundamentals", "Advanced Workshop", "Practical Experience", "Certification", "Mastery"]
    },
    {
        "id": "social_impact_advocate",
        "title": "Social Impact & Advocacy Director",
        "description": "Represent causes and non-profits to influence public policy and secure support for social change.",
        "passion_keywords": ["socialize with purpose", "activism", "public speaking", "helping others", "justice"],
        "skill_keywords": ["lobbying", "fundraising", "campaign management", "public speaking", "networking"],
        "value_keywords": ["impact", "purpose", "justice", "community", "change"],
        "growth_potential": "Medium-High",
        "market_demand": "High",
        "salary_range": (65000, 120000),
        "future_oriented": True,
        "future_relevance": "Essential for human-centric roles",
        "required_skills": ["Stakeholder Management", "Campaign Strategy", "Public Policy Knowledge", "Grant Writing", "Communications"],
        "learning_path": ["Fundamentals", "Advanced Workshop", "Practical Experience", "Certification", "Mastery"]
    },
]


def get_all_careers():
    """Get all available careers"""
    return FUTURE_CAREERS


def get_career_by_id(career_id):
    """Get specific career by ID"""
    for career in FUTURE_CAREERS:
        if career["id"] == career_id:
            return career
    return None


def search_careers_by_keyword(keyword):
    """Search careers matching a keyword"""
    results = []
    keyword_lower = keyword.lower()
    
    for career in FUTURE_CAREERS:
        title_match = keyword_lower in career["title"].lower()
        description_match = keyword_lower in career["description"].lower()
        
        if title_match or description_match:
            results.append(career)
    
    return results
